name: Check

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Init yarn
        run: yarn install
      - name: Lint
        run: yarn lint --max-warnings 0
      - name: Formatting
        run: yarn formatCheck
      - name: Build
        run: yarn build
